workflows:
  financeapp_workflow:
    name: FinanceApp Android build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Ensure Flutter project structure
        script: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "pubspec.yaml not found" >&2
            exit 1
          fi
          # This will (re)create missing platform folders without deleting your lib/
          flutter create . --platforms=android,ios,web
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
